name = "backend"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjRhNDc1NmYtZDA1Zi00ZGRjLTkxYzgtMzc0ZTYxOWI1NjcwIiwidGVuYW50X2lkIjoiZDU4M2FlNmU4M2M1N2RiOTk2YWU0N2MxOGExOWJmZjdiNjQxMTY0MTZhY2Q0MmQyMGU2N2NjOTc3N2JhNjgxNCIsImludGVybmFsX3NlY3JldCI6IjU0MzEyNWRmLTI3MDItNGFjOC04NzgzLWNhMTE5NGQ0ZWRhYSJ9.p2i1uIKVXBd5xkU1z_vtbkvhX3bIZtdoQ2IVaoCZ-00"